# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - arm_Shoulder_Rotation
      - arm_Shoulder_Pitch
      - arm_Elbow
      - arm_Wrist_Pitch
      - arm_Wrist_Roll
    action_ns: follow_joint_trajectory
    default: true
  gripper_controller:
    type: GripperCommand
    joints:
      - arm_Gripper
    action_ns: gripper_cmd
    default: true