"""
Generate a sdf model for the SO-ARM100.

Usage

  python ./generate_sdf.py

Output

  `model.sdf`

    - This file is generated by this script and should not be edited directly.

External dependencies

  `so_arm_100_description`

    - robot description package for the SO-AMR100 robotic arm
    - https://github.com/brukg/SO-100-arm

Local dependencies

  `so_arm_100.urdf.xacro`

    - An xacro file used to assemble the urdf for the arm.
    - The xacro depends on the package `so_arm_100_description`.  -

  `intitial_positions.yaml`

  - Used to configure the initial positions of the SO-ARM100 joints.
"""

import os
import subprocess
import tempfile
import xacro

from copy import deepcopy
from pathlib import Path
from xml.etree import ElementTree as ET

from ament_index_python.packages import get_package_share_directory


# robot name
robot_name = "so_arm_100"

# xacro parameters
prefix = "arm_"
use_sim = "true"
use_topic_hardware_interface = "true"


def generate_sdf_model():
    ardupilot_gz_description_path = os.path.join(
        get_package_share_directory("ardupilot_gz_description")
    )

    # output file
    sdf_file = os.path.join(
        ardupilot_gz_description_path, "models", robot_name, "model.sdf"
    )

    # input files
    initial_positions_file = os.path.join(
        ardupilot_gz_description_path, "models", robot_name, "initial_positions.yaml"
    )

    xacro_file = os.path.join(
        ardupilot_gz_description_path, "models", robot_name, "so_arm_100.urdf.xacro"
    )

    # process xacro and convert to xml.etree
    urdf_doc = ET.fromstring(
        xacro.process_file(
            xacro_file,
            mappings={
                "prefix": prefix,
                "initial_positions_file": str(initial_positions_file),
                "use_sim": use_sim,
                "use_topic_hardware_interface": use_topic_hardware_interface,
            },
        ).toxml()
    )

    # write urdf robot description to temporary file
    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".urdf")
    temp_file_name = temp_file.name

    with open(temp_file_name, "w") as file:
        ET.indent(urdf_doc, space="  ")
        model_urdf = ET.tostring(urdf_doc).decode()
        file.write(str(model_urdf))

    # create sdf from urdf
    with subprocess.Popen(
        ["gz", "sdf", "-p", f"{temp_file_name}"], stdout=subprocess.PIPE
    ) as proc:
        sdf_doc = ET.fromstring(proc.stdout.read())

    # add the ros2_control element back into the sdf
    ros2_control = urdf_doc.find("ros2_control")
    model = sdf_doc.find("model")
    model.append(deepcopy(ros2_control))

    # convert document to string
    ET.indent(sdf_doc, space="  ")
    model_sdf = ET.tostring(sdf_doc).decode()

    # reverse the conversion by gz sdf of the prefix package:// to model://
    # replace model:// prefix with package location
    replace_str = f"model://so_arm_100_description/models"
    with_str = f"package://so_arm_100_description/models"
    model_sdf = model_sdf.replace(replace_str, with_str)

    # write the completed sdf file
    with open(sdf_file, "w") as file:
        file.write(str(model_sdf) + "\n")


def main(args=None):
    generate_sdf_model()


if __name__ == "__main__":
    main()
